//
//  AddReviewViewController.swift
//  App
//
//  Created by Nahuel Zapata on 8/12/18.
//  Copyright (c) 2018 Federico Trimboli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddReviewDisplayLogic: class {
    func displayOnSave(basedOn viewModel: AddReview.Save.ViewModel)
}

class AddReviewViewController: UIViewController, AddReviewDisplayLogic {
    var interactor: AddReviewBusinessLogic?
    var router: (NSObjectProtocol & AddReviewRoutingLogic & AddReviewDataPassing)?

    @IBOutlet weak var reviewerMailTextField: UITextField!
    @IBOutlet weak var starsView: CosmosView!
    @IBOutlet weak var opinionTextView: UITextView!

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    private func setup() {
        let viewController = self
        let interactor = AddReviewInteractor()
        let presenter = AddReviewPresenter()
        let router = AddReviewRouter()

        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    func setUpTextViewDelegate() {
        self.opinionTextView.delegate = self
    }

    @IBAction func saveReview(_ sender: Any) {
        if let validRequest = validateFields() {
            interactor?.prepareForSave(validRequest)
        }
    }

    func validateFields() -> AddReview.Save.Request? {
        guard let reviewerMail = reviewerMailTextField.text else {
            return nil
        }

        guard !opinionTextView.text.isEmpty else {
            return nil
        }

        return AddReview.Save.Request(description: opinionTextView.text, stars: starsView.rating, email: reviewerMail)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        setUpTextViewDelegate()
        changeNavigationTitle("Add review")
    }

    func displayOnSave(basedOn viewModel: AddReview.Save.ViewModel) {
        router?.routeBack()
    }
}

extension UIViewController {
    func changeNavigationTitle(_ title: String) {
        self.navigationItem.title = title
    }
}

extension AddReviewViewController: UITextViewDelegate {
    func textViewDidEndEditing(_ textView: UITextView) {
        if textView.text.isEmpty {
            textView.text = "Add your own review!"
            textView.textColor = .lightGray
        }
    }

    func textViewDidBeginEditing(_ textView: UITextView) {
        if textView.textColor == .lightGray {
            textView.text = nil
            textView.textColor = .black
        }
    }
}
