//
//  TechTalksInteractor.swift
//  App
//
//  Created by Nahuel Zapata on 8/12/18.
//  Copyright (c) 2018 Federico Trimboli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Moya

protocol TechTalksBusinessLogic {
    func performLoad(request: TechTalks.Load.Request)
}

protocol TechTalksDataStore {
    var techTalks: [TechTalk] { get set }
}

class TechTalksInteractor: TechTalksBusinessLogic, TechTalksDataStore {
    var presenter: TechTalksPresentationLogic?
    var worker: TechTalksProvideable? = TechTalksProvider() //FakeTechTalksProvider()
    var techTalks: [TechTalk] = []

    func performLoad(request: TechTalks.Load.Request) {
        worker?.provide(completion: { result in
            do {
                let techTalks = try result.dematerialize()
                self.techTalks = techTalks

                self.presenter?.presentTechTalks(basedOn: TechTalks.Load.Response(result: .success(techTalks)))
            } catch {
                // Add error handling logic
            }
        })
    }
}
