//
//  AddReviewInteractor.swift
//  App
//
//  Created by Nahuel Zapata on 8/12/18.
//  Copyright (c) 2018 Federico Trimboli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Result

protocol AddReviewBusinessLogic {
    func prepareForSave(_ request: AddReview.Save.Request)
}

protocol AddReviewDataStore {
    var techTalk: TechTalk! { get set }
}

class AddReviewInteractor: AddReviewBusinessLogic, AddReviewDataStore {
    var presenter: AddReviewPresentationLogic?
    var provider: AddReviewProvidable?
    var techTalk: TechTalk!

    init(provider: AddReviewProvidable = AddReviewProvider()) {
        self.provider = provider
    }

    func prepareForSave(_ request: AddReview.Save.Request) {
        provider?.provide(reviewId: techTalk.id, request: request, completion: { result in
            do {
                let response = try result.dematerialize()

                self.presenter?.presentSave(basedOn: AddReview.Save.Response(result: .success(response)))
            } catch {
                // Add error handling logic
            }
        })
    }
}
