//
//  AddReviewRouter.swift
//  App
//
//  Created by Nahuel Zapata on 8/12/18.
//  Copyright (c) 2018 Federico Trimboli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddReviewRoutingLogic {

}

protocol AddReviewDataPassing {
    var dataStore: AddReviewDataStore? { get }
}

class AddReviewRouter: NSObject, AddReviewRoutingLogic, AddReviewDataPassing {
    weak var viewController: AddReviewViewController?
    var dataStore: AddReviewDataStore?
    var navigator: Navigatable? // If you don't have the Navigatable protocol, just uncomment the last few lines.

    init(navigator: Navigatable? = Navigator()) {
        self.navigator = navigator
    }
}
