//
//  TechTalksInteractor.swift
//  App
//
//  Created by Nahuel Zapata on 8/12/18.
//  Copyright (c) 2018 Federico Trimboli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TechTalksBusinessLogic {
    func doSomething(request: TechTalks.Something.Request)
}

protocol TechTalksDataStore {
    //var name: String { get set }
}

class TechTalksInteractor: TechTalksBusinessLogic, TechTalksDataStore {
    var presenter: TechTalksPresentationLogic?
    var worker: TechTalksWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: TechTalks.Something.Request) {
        worker = TechTalksWorker()
        worker?.doSomeWork()

        let response = TechTalks.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
