//
//  TechTalksRouter.swift
//  App
//
//  Created by Nahuel Zapata on 8/12/18.
//  Copyright (c) 2018 Federico Trimboli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TechTalksRoutingLogic {

    func routeToDetail()
}

protocol TechTalksDataPassing {
    var dataStore: TechTalksDataStore? { get }
}

class TechTalksRouter: NSObject, TechTalksRoutingLogic, TechTalksDataPassing {
    weak var viewController: TechTalksViewController?
    var dataStore: TechTalksDataStore?
    var navigator: Navigatable?

    init(navigator: Navigatable? = Navigator()) {
        self.navigator = navigator
    }

    func routeToDetail() {
        guard let controller = viewController?.storyboard?.instantiateViewController(withIdentifier: "TechTalkDetailViewController")
        as? TechTalkDetailViewController else {
            return
        }
        var destinationDataStore = controller.router?.dataStore!

        passDetailData(from: dataStore!, to: &destinationDataStore!)
        navigator?.navigateToNextScene(from: viewController!, to: controller)
    }

    func passDetailData(from source: TechTalksDataStore, to destination: inout TechTalkDetailDataStore) {
        if let index = viewController?.feedTableView.indexPathForSelectedRow {
            destination.techTalk = source.techTalks[index.row]
        }
    }
}
