//
//  TechTalkDetailRouter.swift
//  App
//
//  Created by Nahuel Zapata on 8/12/18.
//  Copyright (c) 2018 Federico Trimboli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TechTalkDetailRoutingLogic { }

protocol TechTalkDetailDataPassing {
    var dataStore: TechTalkDetailDataStore? { get }
}

class TechTalkDetailRouter: NSObject, TechTalkDetailRoutingLogic, TechTalkDetailDataPassing {
    weak var viewController: TechTalkDetailViewController?
    var dataStore: TechTalkDetailDataStore?
    var navigator: Navigatable?

    init(navigator: Navigatable? = Navigator()) {
        self.navigator = navigator
    }
}
