//
//  TechTalkDetailRouter.swift
//  App
//
//  Created by Nahuel Zapata on 8/12/18.
//  Copyright (c) 2018 Federico Trimboli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TechTalkDetailRoutingLogic {
    func routeToAddReview()
}

protocol TechTalkDetailDataPassing {
    var dataStore: TechTalkDetailDataStore? { get }
}

class TechTalkDetailRouter: NSObject, TechTalkDetailRoutingLogic, TechTalkDetailDataPassing {
    weak var viewController: TechTalkDetailViewController?
    var dataStore: TechTalkDetailDataStore?
    var navigator: Navigatable?

    init(navigator: Navigatable? = Navigator()) {
        self.navigator = navigator
    }

    func routeToAddReview() {
        guard let controller = viewController?.storyboard?.instantiateViewController(withIdentifier: "AddReviewViewController")
            as? AddReviewViewController else {
                return
        }
        var destinationDataStore = controller.router?.dataStore!
        
        passDetailInfo(from: dataStore!, to: &destinationDataStore!)
        navigator?.navigateToNextScene(from: viewController!, to: controller)
    }
    
    func passDetailInfo(from source: TechTalkDetailDataStore, to destination: inout AddReviewDataStore) {
        destination.techTalk = source.techTalk
    }
}
