//
//  TechTalksPresenter.swift
//  App
//
//  Created by Nahuel Zapata on 8/12/18.
//  Copyright (c) 2018 Federico Trimboli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TechTalksPresentationLogic {
    func presentSomething(response: TechTalks.Something.Response)
}

class TechTalksPresenter: TechTalksPresentationLogic {
    weak var viewController: TechTalksDisplayLogic?

    // MARK: Do something

    func presentSomething(response: TechTalks.Something.Response) {
        let viewModel = TechTalks.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
